### ISSUE TITLE
Gravity only applies to player

### ISSUE THREAD

**Issue by Jackywathy** [Jackywathy/ubiquitous-tribble-game#9]
In scene.vb
UpdatePhysics ONLY checks collisions
however, in handleInput() {scene.vb}, applies const force to player

**Comment by Jackywathy** [comment]
apply constant forces -> check collision -> apply final velocity to location of entities

**Comment by PKBeam** [comment]
Possible fix - Move ApplyConstantForces() to Entity.UpdatePos() sub and call that before collision check

**Comment by PKBeam** [comment]
Gravity still applies to all entities, ApplyConstantForce() is called in all UpdatePos() except player - just move it around

**Comment by PKBeam** [comment]
the collision-beta branch moves `applyConstantForces()` to the sub `updatePos()`, and checks collision afterwards.
